### PR TITLE
Test comparing log-signature with iisignature still doesn't pass.

### PR DESCRIPTION
**Pull request by crispitagorico**
Replaced signatory with iisignature for tests. Test comparing log-signature with iisignature still doesn't pass.

### CODE REVIEW

**Comment by anh-tong** [comment]
Hi Cris,

Thank you for this pull request. I agree that test with `iisignature` can reduce the CI dependency installation time.

Regarding some of the test with log signatures, `signax` currently follows Lyndons basis while `iisignature` mainly uses Hall basis. Using the same basis can correctly match between the two outputs.

Once the test is fixed, the PR can be ready to merge.

**Comment by crispitagorico** [comment]
Hi Anh,  

Thanks for your reply. The Lyndon basis IS a Hall basis, and it is the default choice of basis for the FLA in iisignature. I suspect the issue here is that, as in Patrick's signatory, you are lacking a final linear map to obtain the correct log-signature in the Lyndon basis. See sections 4.3 and A.2.3 in https://arxiv.org/pdf/2001.00706.pdf.

**Comment by anh-tong** [comment]
Thanks for clarifying the point about the basis. Like you said, there are different modes (`words`, `brackets`, `expand`) for logsignature outputs in `signatory` (see [signatory doc](https://signatory.readthedocs.io/en/latest/pages/reference/logsignatures.html#signatory.logsignature)).
And the default (mode `words`) output of `signatory` requires a linear map to correct logsignature ([signatory test file ](https://github.com/patrick-kidger/signatory/blob/2ce3b4af491dde96707b949528cdb648086dbce7/test/test_logsignature.py#L91-L94))

Including different options like this can be good idea for the next upgrade of `signax`.

For now, the test will just focus on the mode `words`.

**Comment by crispitagorico** [comment]
For the log-signature to be mathematically correct, the default option should be mode=`brackets` imo. Computing the log-signature in the correct basis is important for scientific ML applications, RDE solvers etc. For "black-box" deep learnng it might not be necessary. It suffices to compose the current output with a final explicit linear map. I'll have a go at it soon.

**Comment by anh-tong** [comment]
#56

**Comment by anh-tong** [comment]
Sorry for taking so long. I have issued #56 and will try to address this later. The test for log signatures (and some problems in CI) will be fixed in next PR that I'm working on now.

Thank you for this PR.

**Pull request merged**
